spring:
    application:
        name: wallet
    datasource:
        username: ${POSTGRES_USER:api}
        password: ${POSTGRES_PASSWORD:?error}
        url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:api}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
              format_sql: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    liquibase:
        enabled: false
    mvc:
      hiddenmethod:
        filter:
          enabled: true

logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure: ERROR
        root: info
        sql: info
                 
springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /
   

server:
    port: ${APP_PORT:8000}
    tomcat:
        relaxed-query-chars: ["{",  "}", "[", "]"]
      
    servlet:
        context-path: /api/v1